<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
  	<li class="active">Reports</li>
</ul>
<fieldset>
	<legend><i class="icon-bar-chart"></i> Reports</legend>
	<div class="reports col-lg-12">
		<div class="row-fluid">
			<div class="col-lg-4"><a class="btn btn-lg btn-primary" href="/report/school">School Report</a></div>
			<div class="col-lg-4"><a class="btn btn-lg btn-primary" href="/report/teacher">Teacher Report</a></div>
			<div class="col-lg-4"><a class="btn btn-lg btn-primary" href="/report/programme">Programme Report</a></div>
		</div>
	</div>
</fieldset>