<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
  	<li class="active">Reports</li>
</ul>
<fieldset class="report-wrap">
	<legend id="schoolReport"><i class="icon-file-text-alt"></i> School Reports</legend>
	
	<div class="report col-lg-12">
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of Student in Primary School</h4></div>
					<form action="/report/generate/" class="form form-horizontal report-form" method="POST">
						<div class="form-group">
							<label class="col-lg-4 control-label">From</label>
							<div class="col-lg-6">
								<select name="from" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-lg-4 control-label">To</label>
							<div class="col-lg-6">
								<select name="to" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<hr>
						<p class="text-center"><button name="export" value="1" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
						<p class="text-muted text-center">If you leave blank both <b>From</b> and <b>To</b> field, all time data will be exported.</p>
					</form>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of Student in Middle School</h4></div>
					
					<form action="/report/generate/" class="form form-horizontal report-form" method="POST">
						<div class="form-group">
							<label class="col-lg-4 control-label">From</label>
							<div class="col-lg-6">
								<select name="from" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-lg-4 control-label">To</label>
							<div class="col-lg-6">
								<select name="to" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<hr>
						<p class="text-center"><button name="export" value="2" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>

						<p class="text-muted text-center">If you leave blank both <b>From</b> and <b>To</b> field, all time data will be exported.</p>
					</form>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of School in Sub Division / Block</h4></div>
					<form action="/report/generate/" class="form form-horizontal report-form" method="POST">
						<p class="text-center"><button name="export" value="3" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
					</form>
				</div>
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Schools in Sub Division / Block</h4></div>
					<form action="/report/generate/" class="form form-horizontal report-form" method="POST">
						<p class="text-center"><button name="export" value="4" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
					</form>
				</div>
			</div>

 		</div>
	</div>
</fieldset>

<fieldset class="report-wrap">
	<legend id="teacherReport"><i class="icon-file-text-alt"></i> Teacher Reports</legend>
	
	<div class="report col-lg-12">
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of School in Sub Division / Block</h4></div>
					<form action="/report/generate/" class="form form-horizontal report-form" method="POST">
						<p class="text-center"><button name="export" value="1" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
					</form>
				</div>
			</div>
		</div>
	</div>
</fieldset>


<fieldset class="report-wrap">
	<legend id="programmeReport"><i class="icon-file-text-alt"></i> Programme Reports</legend>
	
	<div class="report col-lg-12">
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of School in Sub Division / Block</h4></div>
					<form action="/report/generate/" class="form form-horizontal report-form" method="POST">
						<p class="text-center"><button name="export" value="1" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
					</form>
				</div>
			</div>
		</div>
	</div>
</fieldset>