<ul class="breadcrumb">
	<li><a href="/">Home</a> <span class="divider">/</span></li>
	<li><a href="/report/">Report</a> <span class="divider">/</span></li>
  	<li class="active">School Reports</li>
</ul>
<fieldset>
	<legend><i class="icon-file-text-alt"></i> School Reports</legend>
	<div class="row-fluid">
		<div class="span12">
			<p><i class="icon-info text-warning"></i> <em>Report will be exported in CSV format. This can be opened with MS Excel</em></p>
			<form action="/report/school/" class="form form-inline report-form" method="POST">
				<div class="row-fluid">
					<div class="span12">
						<p>
							<label for="">Enter Year Range</label>
				    		<input type="text" id="year" placeholder="From" class="input-mini">
				    		<input type="text" id="year" placeholder="To" class="input-mini">
				    	</p>
				    	<p>Leave these fields blank to get all time data on the report. To get one year report, enter the same year in From and To field.</p>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn btn-inverse disabled">1</button>
							<button class="span8 btn disabled btn-normal">Number of School in Sub Division / Block</button>
							<button name="export" value="1" class="span3 btn btn-primary">Export</button>
						</div>
					</div>
				</div>
	 			
				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn-inverse btn disabled">2</button>
							<button class="btn disabled span8 btn-normal">Number of Student in Primary School Report</button>
							<button name="export" value="2" class="btn btn-primary span3">Export</button>
						</div>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn-inverse btn disabled">3</button>
							<button class="btn disabled span8 btn-normal">Number of Student in Middle School Report</button>
							<button name="export" value="3" class="btn btn-primary span3">Export</button>
						</div>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn-inverse btn disabled">4</button>
							<button class="btn disabled span8 btn-normal">Teacher Pupils Ratio District Wise</button>
							<button name="export" value="4" class="btn btn-primary span3">Export</button>
						</div>
					</div>
				</div>
	 		</form>
 		</div>
	</div>
</fieldset>