<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
	<li><a href="/report/">Report</a></li>
  	<li class="active">School Reports</li>
</ul>
<fieldset>
	<legend><i class="icon-file-text-alt"></i> School Reports</legend>
	
	<div class="report col-lg-12">
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of School in Sub Division / Block</h4></div>
					<form action="/report/school/" class="form form-horizontal report-form" method="POST">
						<p class="text-center"><button name="export" value="1" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
					</form>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of Student in Primary School</h4></div>
					<form action="/report/school/" class="form form-horizontal report-form" method="POST">
						<div class="form-group">
							<label class="col-lg-4 control-label">From</label>
							<div class="col-lg-6">
								<select name="from" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-lg-4 control-label">To</label>
							<div class="col-lg-6">
								<select name="from" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<hr>
						<p class="text-center"><button name="export" value="2" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>
						<p class="text-muted text-center">If you leave blank both <b>From</b> and <b>To</b> field, all time data will be exported.</p>
					</form>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-success">
					<div class="panel-heading"><h4 class="panel-title">Number of Student in Middle School</h4></div>
					
					<form action="/report/school/" class="form form-horizontal report-form" method="POST">
						<div class="form-group">
							<label class="col-lg-4 control-label">From</label>
							<div class="col-lg-6">
								<select name="from" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-lg-4 control-label">To</label>
							<div class="col-lg-6">
								<select name="from" class="form-control">
									<option value="">----</option>
									<?php for($f=2000;$f<=date('Y');$f++):?>
									<option value="<?php echo $f;?>"><?php echo $f;?></option>
									<?php endfor; ?>
								</select>
							</div>
						</div>
						<hr>
						<p class="text-center"><button name="export" value="3" class="btn btn-lg btn-success">Export CSV <i class="icon-external-link"></i></button></p>

						<p class="text-muted text-center">If you leave blank both <b>From</b> and <b>To</b> field, all time data will be exported.</p>
					</form>
				</div>
			</div>


			<!--
				<div class="row-fluid">
					<div class="span12">
						<p>
							<label for="">Enter Year Range</label>
				    		<input type="text" id="year_from" name="year_from" placeholder="From" class="input-mini">
				    		<input type="text" id="year_to" name="year_to" placeholder="To" class="input-mini">
				    	</p>
				    	<p>Leave these fields blank to get all time data on the report. To get one year report, enter the same year in From and To field.</p>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn btn-inverse disabled">1</button>
							<button class="span8 btn disabled btn-normal">Number of School in Sub Division / Block</button>
							<button name="export" value="1" class="span3 btn btn-primary">Export</button>
						</div>
					</div>
				</div>
	 			
				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn-inverse btn disabled">2</button>
							<button class="btn disabled span8 btn-normal">Number of Student in Primary School Report</button>
							<button name="export" value="2" class="btn btn-primary span3">Export</button>
						</div>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn-inverse btn disabled">3</button>
							<button class="btn disabled span8 btn-normal">Number of Student in Middle School Report</button>
							<button name="export" value="3" class="btn btn-primary span3">Export</button>
						</div>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span12">
						<div class="btn-group span6">
							<button class="span1 btn-inverse btn disabled">4</button>
							<button class="btn disabled span8 btn-normal">Teacher Pupils Ratio District Wise</button>
							<button name="export" value="4" class="btn btn-primary span3">Export</button>
						</div>
					</div>
				</div>
	 		</form>

			-->
 		</div>
	</div>
</fieldset>