 <fieldset>
	<legend>Overview</legend>
	<div class="overview col-lg-12">
		<div class="row-fluid">
			<div class="col-lg-3 item">
				<a class="text-center" href="/school/">
					( <?php echo $this->schoolmodel->stats();?> )
					<span class="name">Schools</span>
					<i class="icon-angle-up"></i>
				</a>
			</div>
			<div class="col-lg-3 item">
				<a class="text-center" href="/program/">
					( <?php echo $this->programmodel->stats();?> )
					<span class="name">Programmes</span>
					<i class="icon-angle-up"></i>
				</a>
			</div>
			<div class="col-lg-3 item">
				<a class="text-center" href="/teacher/">
					( <?php echo $this->teachermodel->stats();?> )
					<span class="name">Teachers</span>
					<i class="icon-angle-up"></i>
				</a>
			</div>
			<div class="col-lg-3 item">
				<a class="text-center" href="/user/">
					( <?php echo $this->usermodel->stats();?> )
					<span class="name">Users</span>
					<i class="icon-angle-up"></i>
				</a>
			</div>
		</div>
	</div>

	<div class="overview col-lg-12">
		<div class="row-fluid">
			<div class="col-lg-3"></div>
			<div class="col-lg-6 item">
				<h2 class="text-center">Teacher : Pupils <i class="icon-angle-right"></i> <span class="label label-danger"><?php echo $this->Ratio();?></span></h2>
				<p class="text-muted text-center">Teacher pupils ratio of <em><?php echo $this->diet_district;?></em> district in <?php echo date('Y');?></p>
			</div>
			<div class="col-lg-3"></div>
		</div>
	</div>
</fieldset>