<ul class="breadcrumb">
	<li><a href="/">Home</a> <span class="divider">/</span></li>
  	<li class="active">School Statistics</li>
</ul>
<fieldset>
	<legend><i class="icon-table"></i> School Statistics</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>School</th>
					<th colspan="2">Year</th>
					<th>I</th>
					<th>II</th>
					<th>III</th>
					<th>IV</th>
					<th>V</th>
					<th>VI</th>
					<th>VII</th>
					<th>VIII</th>
					<th>Total</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>13)); ?>

		<?php foreach($this->data as $row): ?>
			<tr>
				<td rowspan="3"><?php echo $row->name;?></td>
				<td rowspan="3"><?php echo $row->year;?></td>
				<th>Boys</th>
				<td><?php echo $row->boys_1;?></td>
				<td><?php echo $row->boys_2;?></td>
				<td><?php echo $row->boys_3;?></td>
				<td><?php echo $row->boys_4;?></td>
				<td><?php echo $row->boys_5;?></td>
				<td><?php echo $row->boys_6;?></td>
				<td><?php echo $row->boys_7;?></td>
				<td><?php echo $row->boys_8;?></td>
				<td><?php echo $row->boys_1 + $row->boys_2 + $row->boys_3 + $row->boys_4 + $row->boys_5 + $row->boys_6 + $row->boys_7 + $row->boys_8;?></td>
				<td rowspan="3">
					<a class="btn btn-mini btn-primary action-tooltip" href="/school-statistic/edit/id/<?php echo $row->id;?>" title="Edit Statistic"><i class="icon-pencil"></i></a>
					
					<?php if($this->user->role == 'administrator'):?>
					<a class="btn btn-mini btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete <?php echo $row->year;?> statistic for <?php echo $row->name;?>?')" href="/school-statistic/remove/id/<?php echo $row->id;?>" title="Delete Statistic"><i class="icon-remove"></i></a>
					<?php endif;?>
				</td>
			</tr>
			<tr>
				<th>Girls</th>
				<td><?php echo $row->girls_1;?></td>
				<td><?php echo $row->girls_2;?></td>
				<td><?php echo $row->girls_3;?></td>
				<td><?php echo $row->girls_4;?></td>
				<td><?php echo $row->girls_5;?></td>
				<td><?php echo $row->girls_6;?></td>
				<td><?php echo $row->girls_7;?></td>
				<td><?php echo $row->girls_8;?></td>
				<td><?php echo $row->girls_1 + $row->girls_2 + $row->girls_3 + $row->girls_4 + $row->girls_5 + $row->girls_6 + $row->girls_7 + $row->girls_8;?></td>
			</tr>
			<tr>
				<th>Total</th>
				<td><?php echo $row->boys_1 + $row->girls_1;?></td>
				<td><?php echo $row->boys_2 + $row->girls_2;?></td>
				<td><?php echo $row->boys_3 + $row->girls_3;?></td>
				<td><?php echo $row->boys_4 + $row->girls_4;?></td>
				<td><?php echo $row->boys_5 + $row->girls_5;?></td>
				<td><?php echo $row->boys_6 + $row->girls_6;?></td>
				<td><?php echo $row->boys_7 + $row->girls_7;?></td>
				<td><?php echo $row->boys_8 + $row->girls_8;?></td>
				<th><?php echo $row->boys_1 + $row->boys_2 + $row->boys_3 + $row->boys_4 + $row->girls_1 + $row->girls_2 + $row->girls_3 + $row->girls_4 + $row->boys_5 + $row->boys_6 + $row->boys_7 + $row->boys_8 + $row->girls_5 + $row->girls_6 + $row->girls_7 + $row->girls_8;?></th>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="13" class="text-right"><span>Total Statistics: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>