<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Programmes</li>
</ul>

<fieldset>
	<legend><i class="icon-list-ul"></i> List Programmes</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Duration</th>
					<th>Target</th>
					<th class="col-2"></th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>5)); ?>

		<?php foreach($this->data as $key=>$row): ?>
			<tr>
				<td><?php echo ($key+1) + ($this->data->getItemCountPerPage()*($this->data->getCurrentPageNumber() - 1));?></td>
				<td><?php echo $row->name;?></td>
				<td><?php echo $row->duration;?> days</td>
				<td><?php echo $row->target;?></td>
				<td>					
					<a class="btn btn-xs btn-info action-tooltip" data-target="#view_programme_<?php echo $row->id;?>" data-toggle="modal" href="/program/view/id/<?php echo $row->id;?>" title="View Programme"><i class="icon-eye-open"></i></a>

					<a class="btn btn-xs btn-info action-tooltip" href="/program/edit/id/<?php echo $row->id;?>" title="Edit Programme"><i class="icon-pencil"></i></a>

					<a class="btn btn-xs btn-info action-tooltip" href="/program/trainee/id/<?php echo $row->id;?>" title="Manage Trainees"><i class="icon-group"></i></a>
					
					<?php if($this->user->role == 'administrator'):?>
					<a class="btn btn-xs btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete programme \'<?php echo $row->name;?>\'?')" href="/program/remove/id/<?php echo $row->id;?>" title="Delete Programme"><i class="icon-trash"></i></a>
					<?php endif;?>

					<div id="view_programme_<?php echo $row->id;?>" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
									<h3 id="view_programme_<?php echo $row->id;?>_label">"<?php echo $row->name;?>"</h3>
								</div>
								<div class="modal-body">
								</div>
								<div class="modal-footer">
									<button class="btn btn-info btn-sm" data-dismiss="modal" aria-hidden="true">Close</button>
								</div>
							</div>
						</div>
					</div>

				</td>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="5" class="text-right"><span class="text-info">Total Programmes: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>