<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Programmes</li>
</ul>

<fieldset>
	<legend><i class="icon-table"></i> List Programmes</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Duration</th>
					<th>Target</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>4)); ?>

		<?php foreach($this->data as $row): ?>
			<tr>
				<td><?php echo $row->name;?></td>
				<td><?php echo $row->duration;?> days</td>
				<td><?php echo $row->target;?></td>
				<td>					
					<a class="btn btn-mini btn-primary action-tooltip" data-target="#view_programme_<?php echo $row->id;?>" data-toggle="modal" href="/program/view/id/<?php echo $row->id;?>" title="View Programme"><i class="icon-eye-open"></i></a>

					<a class="btn btn-mini btn-primary action-tooltip" href="/program/edit/id/<?php echo $row->id;?>" title="Edit Programme"><i class="icon-pencil"></i></a>

					<a class="btn btn-mini btn-primary action-tooltip" href="/program/trainee/id/<?php echo $row->id;?>" title="Manage Trainees"><i class="icon-cog"></i></a>
					
					<a class="btn btn-mini btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete programme \'<?php echo $row->name;?>\'?')" href="/program/remove/id/<?php echo $row->id;?>" title="Delete Programme"><i class="icon-remove"></i></a>

					<div id="view_programme_<?php echo $row->id;?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="view_programme_<?php echo $row->id;?>_label" aria-hidden="true">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
							<h3 id="view_programme_<?php echo $row->id;?>_label">"<?php echo $row->name;?>"</h3>
						</div>
						<div class="modal-body">
						</div>
						<div class="modal-footer">
							<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						</div>
					</div>

				</td>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="4" class="text-right"><span>Total Programmes: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>