<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
  	<li><a href="/program/">Programmes</a></li>
  	<li class="active"><?php echo $this->program->name;?> &rsaquo; Trainee List</li>
</ul>
<fieldset>
	<legend><i class="icon-list-ul"></i> <?php echo $this->program->name;?> Trainee List</legend>

	<form class="form form-inline form-toolbar" action="" method="post">
		<button class="btn btn-success btn-xs pull-right" type="button" onclick="window.location='/program/add-trainee/id/<?php echo $this->program->id;?>'"><i class="icon-plus"></i> Add Trainee</a></button>
	</form>

	<div class="row-fluid">
		<table class="table table-striped table-condensed table-hover teacher-training-list">
			<thead>
				<tr>
					<th>#</th>
					<th>Teacher Name</th>
					<th>From</th>
					<th>To</th>
					<th>School</th>
					<th>Status</th>
					<th></th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>7)); ?>

		<?php foreach($this->data as $key=>$row): ?>
			<tr>
				<td><?php echo ($key+1) + ($this->data->getItemCountPerPage()*($this->data->getCurrentPageNumber() - 1));?></td>
				<td>
					<a href="/teacher/view/id/<?php echo $row->teacher_id;?>" data-target="#view_teacher_<?php echo $row->id;?>" target="_blank" data-toggle="modal" title="Click to view detail" class="action-tooltip"><?php echo $row->teacher_name;?></a>

					<div id="view_teacher_<?php echo $row->id;?>" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
									<h3 id="view_teacher_<?php echo $row->id;?>_label">Teacher: <?php echo $row->teacher_name;?></h3>
								</div>
								<div class="modal-body">
								</div>
								<div class="modal-footer">
									<button class="btn btn-info btn-sm" data-dismiss="modal" aria-hidden="true">Close</button>
								</div>
							</div>
						</div>
					</div>					
				</td>
				<td><a href="/teacher/change-training-date/id/<?php echo $row->id;?>/field/from/" class="action-tooltip change-training-date" title="Click to change this date"><?php echo $this->Date($row->from, 'dS F, Y');?></a></td>
				<td><a href="/teacher/change-training-date/id/<?php echo $row->id;?>/field/to/" class="action-tooltip change-training-date" title="Click to change this date"><?php echo $this->Date($row->to, 'dS F, Y');?></a></td>
				<td><?php echo $this->School($row->school_id)->name; ?></td>
				<td>
					<?php
					$btn = 'primary';
					switch($row->status)
					{
						case 'Active':
							$btn = 'primary';
							break;
						case 'Completed':
							$btn = 'success';
							break;
						case 'Cancelled':
							$btn = 'danger';
							break;
						case 'Withheld':
							$btn = 'warning';
							break;
					}

					?>
					<div class="btn-group teacher-change-training-status">
						<button class="btn btn-xs btn-<?php echo $btn;?>"><?php echo ($row->status);?></button>
						<button class="btn btn-xs btn-<?php echo $btn;?> dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/active/">Active</a></li>
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/completed/">Completed</a></li>
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/withheld/">Withheld</a></li>
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/cancelled/">Cancelled</a></li>
						</ul>
					</div>
				</td>
				<?php if($this->user->role == 'administrator'):?>
				<td>
					<a class="btn btn-xs btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete this training?')" href="/teacher/remove-training/id/<?php echo $row->id;?>" title="Delete Training"><i class="icon-trash"></i></a>
				</td>
				<?php endif;?>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="7" class="text-right"><span class="text-info">Total Training: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>

<script>
jQuery(function(){
	jQuery('.change-training-date').on('click', function(evt){
		evt.preventDefault(true);
	});

	jQuery('.change-training-date').pickadate({
	    showMonthsShort: true,
		onSet: function(event) {
	        var element = this.$node;

	        $.ajax({
	        	url: element.attr('href'),
	        	data: 'date='+event.select,
	        	beforeSend: function(){
	        		element.text('Please wait...');
	        	}
	        })
	        .done(function(result){
        		element.text(result.date);
	        });
	    }
	});

	jQuery('.teacher-change-training-status .status').on('click', function(evt){
		evt.preventDefault(true);
		var _this = $(this);
		var row = _this.closest('td');

		jQuery.ajax({
			url: _this.attr('href'),
			beforeSend: function(){
				row.find('button').eq(0).text('Please wait...');
			}
		})
		.done(function(result){
			row.find('button').eq(0).text(_this.text());
			row.find('button').removeClass('btn-primary').removeClass('btn-danger').removeClass('btn-warning').removeClass('btn-success');

			if(_this.text() == 'Active')
				row.find('button').addClass('btn-primary');
			else if(_this.text() == 'Completed')
				row.find('button').addClass('btn-success');
			else if(_this.text() == 'Cancelled')
				row.find('button').addClass('btn-danger');
			else if(_this.text() == 'Withheld')
				row.find('button').addClass('btn-warning');
		});
	});

});
</script>