<?php $this->LoadTemplate($this->zone, $this->template); ?><!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">	
	<?php echo $this->headTitle(); ?>
	
	<?php echo $this->headLink(); ?>
	
	<?php echo $this->headScript(); ?>
	
	<?php echo $this->headStyle(); ?>
	<style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #D0DF80;
      }

      .form-signin {
        max-width: 400px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        /*background-color: #fff;*/
        /*border: 1px solid #e5e5e5;*/
        /*-webkit-border-radius: 5px;*/
           /*-moz-border-radius: 5px;*/
                /*border-radius: 5px;*/
        /*-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);*/
           /*-moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);*/
                /*box-shadow: 0 1px 2px rgba(0,0,0,.05);*/
      }
      .form-signin .form-signin-heading {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
        -webkit-box-sizing: border-box;
           -moz-box-sizing: border-box;
                box-sizing: border-box;
      }
      .form-signin input[type="text"]:focus,
      .form-signin input[type="password"]:focus {
        z-index: 2;
      }
      .form-signin input[type="text"] {
        margin-bottom: -1px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
      #login {
        margin-top:10px;
      }
	</style>
</head>
<body class="<?php echo $this->actionName; ?> <?php echo $this->controllerName; ?> fl full">
	<div class="container">
    <div class="form-signin">
      <h2 class="form-signin-heading"><i class="icon-signin"></i> Please sign in</h2>
      <?php echo $this->form;?>
      <?php echo $this->Alert();?>
    </div>
    <div class="container-fluid">
      <p class="muted credit text-center">&copy; Copyright Reserved. DIET <?php echo $this->diet_district;?> Traning Management System.</p>
    </div>    
  </div>
</body>
</html>