<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Teachers</li>
</ul>
<fieldset>
	<legend><i class="icon-table"></i> List Teachers</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-condensed table-hover">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>School</th>
					<th>Qualification</th>
					<th>Status</th>
					<th><span class="action-tooltip" title="Number of training attended">Training</span></th>
					<th></th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>7)); ?>

		<?php foreach($this->data as $key=>$row): ?>
			<tr>
				<td><?php echo ($key+1) + ($this->data->getItemCountPerPage()*($this->data->getCurrentPageNumber() - 1));?></td>
				<td><?php echo $row->name;?></td>
				<td><?php echo $this->School($row->school_id)->name;?></td>
				<td><?php echo $row->educational_qualification;?></td>
				<td><?php echo $row->status;?></td>
				<td><?php echo $this->trainingmodel->teacherCount($row->id);?></td>
				<td>					
					<a class="btn btn-xs btn-info action-tooltip" data-target="#view_teacher_<?php echo $row->id;?>" data-toggle="modal" href="/teacher/view/id/<?php echo $row->id;?>/" title="View Teacher"><i class="icon-eye-open"></i></a>

					<a class="btn btn-xs btn-info action-tooltip" href="/teacher/edit/id/<?php echo $row->id;?>" title="Edit Teacher"><i class="icon-pencil"></i></a>

					<a class="btn btn-xs btn-info action-tooltip" href="/teacher/training/id/<?php echo $row->id;?>" title="Manage Training"><i class="icon-cog"></i></a>
					
					<?php if($this->user->role == 'administrator'):?>
					<a class="btn btn-xs btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete teacher \'<?php echo $row->name;?>\'?')" href="/teacher/remove/id/<?php echo $row->id;?>" title="Delete Teacher"><i class="icon-remove"></i></a>
					<?php endif;?>

					<div id="view_teacher_<?php echo $row->id;?>" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
									<h3 id="view_teacher_<?php echo $row->id;?>_label">Teacher: <?php echo $row->name;?></h3>
								</div>
								<div class="modal-body">
									<img src="/templates/default/default/images/loader-velocity.gif" alt="" />
								</div>
								<div class="modal-footer">
									<button class="btn btn-info btn-sm" data-dismiss="modal" aria-hidden="true">Close</button>
								</div>

							</div>
						</div>
					</div>

				</td>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="7" class="text-right"><span class="text-info">Total Teachers: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>

<script>
$(function(){
	if($("#district").val() != '')
		getByDistrict($("#district").val());

	if($("#advanced").val().trim() == 'Show More Filter')
	{
		$("#professional_qualification, #tet, #status, #main_subject_taught, #year_of_retirement, #no_of_training, #search").hide();
		$("#date_of_joining").parent().hide();

		$("#professional_qualification, #tet, #status, #main_subject_taught, #year_of_retirement, #no_of_training, #search").val('');
	}

	$("#advanced").on("click", function(){
		$("#professional_qualification, #tet, #status, #main_subject_taught, #year_of_retirement, #no_of_training, #search").toggle();
		$("#date_of_joining").parent().toggle();

		if($(this).val().trim() == 'Show More Filter')
		{
			$(this).val('Show Less Filter').text('Show Less Filter');
			$("#as").val(1);
		}
		else if($(this).val().trim() == 'Show Less Filter')
		{
			$("#professional_qualification, #tet, #status, #main_subject_taught, #year_of_retirement, #no_of_training, #search").val('');
			$(this).val('Show More Filter').text('Show More Filter');
			$("#as").val(0);
		}
	});
});

function getByDistrict(district)
{
	$.ajax({
		url: '/sub-division/fetch-by-district/district/'+district
	})
	.done(function(result){
		var current = $('#sub_division').val();
		var opts = '<option value="">All Sub Division / Block</option>';
		$(result).each(function(k,data){
			opts += '<option value="'+data.name+'">'+data.name+'</option>';
		});

		$('#sub_division').html(opts);
		$('#sub_division').val(current);
	});
}
</script>