<ul class="breadcrumb">
	<li><a href="/">Home</a> <span class="divider">/</span></li>
  	<li><a href="/teacher/">Teachers</a> <span class="divider">/</span></li>
  	<li class="active"><?php echo $this->teacher->name;?> &rsaquo; Training List</li>
</ul>
<fieldset>
	<legend><i class="icon-table"></i> <?php echo $this->teacher->name;?> Training List <a class="btn btn-success btn-mini pull-right" href="/teacher/add-training/id/<?php echo $this->teacher->id;?>">ADD TRAINING</a></legend>
	<div class="row-fluid">
		<table class="table table-striped table-bordered table-hover teacher-training-list">
			<thead>
				<tr>
					<th>Programme</th>
					<th>From</th>
					<th>To</th>
					<th>Status</th>
					<?php if($this->user->role == 'administrator'):?>
					<th>Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
		
		<?php
		if($this->user->role == 'administrator')
			echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>5));
		else
			echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>4));
		?>

		<?php foreach($this->data as $row): ?>
			<tr>
				<td><?php echo $this->Program($row->program_id)->name;?></td>
				
				<td><a href="/teacher/change-training-date/id/<?php echo $row->id;?>/field/from/" class="action-tooltip change-training-date" title="Click to change this date"><?php echo $this->Date($row->from, 'dS F, Y');?></a></td>
				<td><a href="/teacher/change-training-date/id/<?php echo $row->id;?>/field/to/" class="action-tooltip change-training-date" title="Click to change this date"><?php echo $this->Date($row->to, 'dS F, Y');?></a></td>
				<td>
					<?php
					$btn = 'primary';
					switch($row->status)
					{
						case 'Active':
							$btn = 'primary';
							break;
						case 'Completed':
							$btn = 'success';
							break;
						case 'Cancelled':
							$btn = 'danger';
							break;
						case 'Withheld':
							$btn = 'warning';
							break;
					}

					?>
					<div class="btn-group teacher-change-training-status">
						<button class="btn btn-mini btn-<?php echo $btn;?>"><?php echo strtoupper($row->status);?></button>
						<button class="btn btn-mini btn-<?php echo $btn;?> dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/active/">Active</a></li>
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/completed/">Completed</a></li>
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/withheld/">Withheld</a></li>
							<li><a class="status" href="/teacher/change-training-status/id/<?php echo $row->id;?>/status/cancelled/">Cancelled</a></li>
						</ul>
					</div>
				</td>

				<?php if($this->user->role == 'administrator'):?>
				<td>
					<a class="btn btn-mini btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete this training?')" href="/teacher/remove-training/id/<?php echo $row->id;?>" title="Delete Training"><i class="icon-remove"></i></a>
				</td>
				<?php endif;?>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<?php if($this->user->role == 'administrator'):?>
					<th colspan="5" class="text-right"><span>Total Training: <?php echo $this->data->getTotalItemCount(); ?></span></th>
					<?php else:?>
					<th colspan="4" class="text-right"><span>Total Training: <?php echo $this->data->getTotalItemCount(); ?></span></th>
					<?php endif;?>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>

<script>
jQuery(function(){
	jQuery('.change-training-date').on('click', function(evt){
		evt.preventDefault(true);
	});

	jQuery('.change-training-date').pickadate({
	    showMonthsShort: true,
		onSet: function(event) {
	        var element = this.$node;

	        $.ajax({
	        	url: element.attr('href'),
	        	data: 'date='+event.select,
	        	beforeSend: function(){
	        		element.text('Please Wait...');
	        	}
	        })
	        .done(function(result){
        		element.text(result.date);
	        });
	    }
	});

	jQuery('.teacher-change-training-status .status').on('click', function(evt){
		evt.preventDefault(true);
		var _this = $(this);
		var row = _this.closest('td');

		jQuery.ajax({
			url: _this.attr('href'),
			beforeSend: function(){
				row.find('button').eq(0).text('Please Wait...');
			}
		})
		.done(function(result){
			row.find('button').eq(0).text(_this.text().toUpperCase());
			row.find('button').removeClass('btn-primary').removeClass('btn-danger').removeClass('btn-warning').removeClass('btn-success');

			if(_this.text() == 'Active')
				row.find('button').addClass('btn-primary');
			else if(_this.text() == 'Completed')
				row.find('button').addClass('btn-success');
			else if(_this.text() == 'Cancelled')
				row.find('button').addClass('btn-danger');
			else if(_this.text() == 'Withheld')
				row.find('button').addClass('btn-warning');
		});
	});

});
</script>