<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
	<li><a href="/school/">Schools</a></li>
	<li><a href="/school/statistics/id/<?php echo $this->school->id;?>"><?php echo $this->school->name;?> &rsaquo; Statistics</a></li>
  	<li class="active">Edit Statistic</li>
</ul>
<fieldset>
	<legend><i class="icon-table"></i> <?php echo $this->school->name;?> &rsaquo; Edit Statistic</legend>
	<div class="row-fluid">
		<?php echo $this->form;?>
	</div>
</fieldset>
<script>
$(function(){
	$('.boys').each(function(){
		var element = $(this).closest('.input-append');
		var wrap = $(this).closest('.control-group');
		wrap.next().find('.input-append').before(element);
		wrap.next().find('.input-append').eq(1).before("&nbsp;&nbsp;");
		wrap.remove();
	});
});
</script>