<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
  	<li class="active">Schools</li>
</ul>
<fieldset>
	<legend><i class="icon-list-ul"></i> List Schools</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-condensed table-hover">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Level</th>
					<th>Type</th>
					<th>Established</th>
					<th>Phone</th>
					<th>Address</th>
					<th>No of Teachers</th>
					<th></th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>9)); ?>

		<?php foreach($this->data as $key=>$row): ?>
			<tr>
				<td><?php echo ($key+1) + ($this->data->getItemCountPerPage()*($this->data->getCurrentPageNumber() - 1));?></td>
				<td><?php echo $row->name;?></td>
				<td><?php echo $row->level;?></td>
				<td><?php echo $row->type;?></td>
				<td><?php echo $row->year_of_establishment;?></td>
				<td><?php echo $row->phone;?></td>
				<td><?php echo $row->address;?></td>
				<td><?php echo $row->no_of_teachers;?></td>
				<td>					
					<a class="btn btn-xs btn-info action-tooltip" data-target="#view_school_<?php echo $row->id;?>" data-toggle="modal" href="/school/view/id/<?php echo $row->id;?>" title="View School"><i class="icon-eye-open"></i></a>

					<a class="btn btn-xs btn-info action-tooltip" href="/school/edit/id/<?php echo $row->id;?>" title="Edit School"><i class="icon-pencil"></i></a>

					<a class="btn btn-xs btn-info action-tooltip" href="/school/statistics/id/<?php echo $row->id;?>" title="View Statistics"><i class="icon-bar-chart"></i></a>

					<?php if($this->user->role == 'administrator'):?>
					<a class="btn btn-xs btn-info action-tooltip" href="/school/new-statistic/id/<?php echo $row->id;?>" title="New Statistic"><i class="icon-plus"></i></a>

					<a class="btn btn-xs btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete school \'<?php echo $row->name;?>\'?')" href="/school/remove/id/<?php echo $row->id;?>" title="Delete School"><i class="icon-trash"></i></a>
					<?php endif;?>

					<div id="view_school_<?php echo $row->id;?>" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
									<h3 id="view_school_<?php echo $row->id;?>_label">"<?php echo $row->name;?>"</h3>
								</div>
								<div class="modal-body">
								</div>
								<div class="modal-footer">
									<button class="btn btn-info btn-sm" data-dismiss="modal" aria-hidden="true">Close</button>
								</div>
							</div>
						</div>
					</div>					
				</td>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="9" class="text-right"><span class="text-info">Total Schools: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>
<script>
$(function(){
	if($("#district").val() != '')
		getByDistrict($("#district").val());
});

function getByDistrict(district)
{
	$.ajax({
		url: '/sub-division/fetch-by-district/district/'+district
	})
	.done(function(result){
		var current = $('#sub_division').val();
		var opts = '<option value="">All Sub Division / Block</option>';
		$(result).each(function(k,data){
			opts += '<option value="'+data.name+'">'+data.name+'</option>';
		});

		$('#sub_division').html(opts);
		$('#sub_division').val(current);
	});
}
</script>