<ul class="breadcrumb">
	<li><a href="/">Home</a> <span class="divider">/</span></li>
	<li><a href="/school/">Schools</a> <span class="divider">/</span></li>
  	<li class="active">Statistics</li>
</ul>
<fieldset>
	<legend><i class="icon-table"></i> List Schools</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Type</th>
					<th>Established</th>
					<th>Phone</th>
					<th>Address</th>
					<th>No of Teachers</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>7)); ?>

		<?php foreach($this->data as $row): ?>
			<tr>
				<td><?php echo $row->name;?></td>
				<td><?php echo $row->type;?></td>
				<td><?php echo $row->year_of_establishment;?></td>
				<td><?php echo $row->phone;?></td>
				<td><?php echo $row->address;?></td>
				<td><?php echo $row->no_of_teachers;?></td>
				<td>					
					<a class="btn btn-mini btn-primary action-tooltip" href="/school/edit/id/<?php echo $row->id;?>" title="Edit School"><i class="icon-pencil"></i></a>
					
					<?php if($this->user->role == 'administrator'):?>
					<a class="btn btn-mini btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete school \'<?php echo $row->name;?>\'?')" href="/school/remove/id/<?php echo $row->id;?>" title="Delete School"><i class="icon-remove"></i></a>
					<?php endif;?>
				</td>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="7" class="text-right"><span>Total Schools: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>