<ul class="breadcrumb">
	<li><a href="/">Home</a></li>
	<li><a href="/school/">Schools</a></li>
  	<li class="active"><?php echo $this->school->name;?> &rsaquo; Statistics</li>
</ul>
<fieldset>
	<legend><i class="icon-bar-chart"></i> <?php echo $this->school->name;?> &rsaquo; Statistics</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-bordered table-condensed table-hover">
			<thead>
				<tr>
					<th colspan="2">Year</th>
					<?php if($this->school->level == "Primary School"): ?>
					<th>Pre</th>
					<th>I</th>
					<th>II</th>
					<th>III</th>
					<th>IV</th>
					<?php elseif($this->school->level == "Middle School"): ?>
					<th>V</th>
					<th>VI</th>
					<th>VII</th>
					<th>VIII</th>
					<?php endif;?>
					<th>Total</th>
					<th class="col-lg-1">Teachers</th>
					<th class="col-lg-2">Teacher : Pupils</th>
					<th class="col-lg-1"></th>
				</tr>
			</thead>
			<tbody>

		<?php if($this->school->level == "Primary School"): ?>
		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>11)); ?>
		<?php elseif($this->school->level == "Middle School"): ?>
		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>10)); ?>
		<?php endif;?>

		<?php foreach($this->data as $row): ?>
			<tr>
				<td rowspan="3"><?php echo $row->year;?></td>
				<th>Boys</th>
				<?php if($this->school->level == "Primary School"): ?>
				<td><?php echo $row->boys_pre;?></td>
				<td><?php echo $row->boys_1;?></td>
				<td><?php echo $row->boys_2;?></td>
				<td><?php echo $row->boys_3;?></td>
				<td><?php echo $row->boys_4;?></td>
				<td><?php echo $row->boys_pre + $row->boys_1 + $row->boys_2 + $row->boys_3 + $row->boys_4;?></td>
				<?php elseif($this->school->level == "Middle School"): ?>
				<td><?php echo $row->boys_5;?></td>
				<td><?php echo $row->boys_6;?></td>
				<td><?php echo $row->boys_7;?></td>
				<td><?php echo $row->boys_8;?></td>
				<td><?php echo $row->boys_5 + $row->boys_6 + $row->boys_7 + $row->boys_8;?></td>
				<?php endif;?>
				<td rowspan="3"><?php echo $row->teachers;?></td>
				<td rowspan="3"><?php

				if($this->school->level == 'Primary School' && $row->teachers > 0)
					echo "1 : ".round(($row->boys_1 + $row->boys_2 + $row->boys_3 + $row->boys_4 + $row->girls_1 + $row->girls_2 + $row->girls_3 + $row->girls_4)/$row->teachers);
				else if($this->school->level == 'Middle School' && $row->teachers > 0)
					echo "1 : ".round(($row->boys_5 + $row->boys_6 + $row->boys_7 + $row->boys_8 + $row->girls_5 + $row->girls_6 + $row->girls_7 + $row->girls_8)/$row->teachers);
				else
					echo 'n/a';
				?></td>
				<td rowspan="3">
					<a class="btn btn-xs btn-info action-tooltip" href="/school/edit-statistic/id/<?php echo $row->id;?>" title="Edit Statistic"><i class="icon-pencil"></i></a>
					
					<?php if($this->user->role == 'administrator'):?>
					<a class="btn btn-xs btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete <?php echo $row->year;?> statistic?')" href="/school/remove-statistic/id/<?php echo $row->id;?>" title="Delete Statistic"><i class="icon-trash"></i></a>
					<?php endif;?>
				</td>
			</tr>
			<tr>
				<th>Girls</th>
				<?php if($this->school->level == "Primary School"): ?>
				<td><?php echo $row->girls_pre;?></td>
				<td><?php echo $row->girls_1;?></td>
				<td><?php echo $row->girls_2;?></td>
				<td><?php echo $row->girls_3;?></td>
				<td><?php echo $row->girls_4;?></td>
				<td><?php echo $row->girls_pre + $row->girls_1 + $row->girls_2 + $row->girls_3 + $row->girls_4;?></td>
				<?php elseif($this->school->level == "Middle School"): ?>
				<td><?php echo $row->girls_5;?></td>
				<td><?php echo $row->girls_6;?></td>
				<td><?php echo $row->girls_7;?></td>
				<td><?php echo $row->girls_8;?></td>
				<td><?php echo $row->girls_5 + $row->girls_6 + $row->girls_7 + $row->girls_8;?></td>
				<?php endif;?>
			</tr>
			<tr>
				<th>Total</th>
				<?php if($this->school->level == "Primary School"): ?>
				<td><?php echo $row->boys_pre + $row->girls_pre;?></td>
				<td><?php echo $row->boys_1 + $row->girls_1;?></td>
				<td><?php echo $row->boys_2 + $row->girls_2;?></td>
				<td><?php echo $row->boys_3 + $row->girls_3;?></td>
				<td><?php echo $row->boys_4 + $row->girls_4;?></td>
				<th><?php echo $row->boys_pre + $row->boys_1 + $row->boys_2 + $row->boys_3 + $row->boys_4 + $row->girls_pre + $row->girls_1 + $row->girls_2 + $row->girls_3 + $row->girls_4;?></th>
				<?php elseif($this->school->level == "Middle School"): ?>
				<td><?php echo $row->boys_5 + $row->girls_5;?></td>
				<td><?php echo $row->boys_6 + $row->girls_6;?></td>
				<td><?php echo $row->boys_7 + $row->girls_7;?></td>
				<td><?php echo $row->boys_8 + $row->girls_8;?></td>
				<th><?php echo $row->boys_5 + $row->boys_6 + $row->boys_7 + $row->boys_8 + $row->girls_5 + $row->girls_6 + $row->girls_7 + $row->girls_8;?></th>
				<?php endif;?>
			</tr>			
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<?php if($this->school->level == "Primary School"): ?>
					<th colspan="11" class="text-right"><span class="text-info">Total Records: <?php echo $this->data->getTotalItemCount(); ?></span></th>
					<?php elseif($this->school->level == "Middle School"): ?>
					<th colspan="10" class="text-right"><span class="text-info">Total Records: <?php echo $this->data->getTotalItemCount(); ?></span></th>
					<?php endif;?>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>