<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Backup</li>
</ul>

<fieldset>
	<legend><i class="icon-table"></i> Backups</legend>
	<div class="row-fluid">

		<?php echo $this->form;?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>#</th>
					<th>Backup Date</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>

		<?php echo $this->partial('partials/table-empty.phtml', array('data'=>$this->data,'colspan'=>3)); ?>

		<?php foreach($this->data as $key=>$row): ?>
			<tr>
				<td><?php echo ($key+1) + ($this->data->getItemCountPerPage()*($this->data->getCurrentPageNumber() - 1));?></td>
				<td><?php echo $this->Date($row->created_at, 'd M Y, h:i A');?></td>
				<td>					
					<a class="btn btn-mini btn-info action-tooltip" href="<?php echo $row->file;?>" title="Download"><i class="icon-download"></i></a>

					<a class="btn btn-mini btn-danger action-tooltip" onclick="return confirm('Are you sure you want to delete this backup?')" href="/backup/remove/id/<?php echo $row->id;?>" title="Remove Backup"><i class="icon-trash"></i></a>
				</td>
			</tr>
		<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="3" class="text-right"><span>Total Backups: <?php echo $this->data->getTotalItemCount(); ?></span></th>
				</tr>
			</tfoot>
		</table>

		<?php echo $this->data; ?>
	</div>
</fieldset>